// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: payroll.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Payroll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmpId         string                 `protobuf:"bytes,2,opt,name=emp_id,json=empId,proto3" json:"emp_id,omitempty"`
	EmpName       string                 `protobuf:"bytes,3,opt,name=emp_name,json=empName,proto3" json:"emp_name,omitempty"`
	Salary        float64                `protobuf:"fixed64,4,opt,name=salary,proto3" json:"salary,omitempty"`
	Month         string                 `protobuf:"bytes,5,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payroll) Reset() {
	*x = Payroll{}
	mi := &file_payroll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payroll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payroll) ProtoMessage() {}

func (x *Payroll) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payroll.ProtoReflect.Descriptor instead.
func (*Payroll) Descriptor() ([]byte, []int) {
	return file_payroll_proto_rawDescGZIP(), []int{0}
}

func (x *Payroll) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payroll) GetEmpId() string {
	if x != nil {
		return x.EmpId
	}
	return ""
}

func (x *Payroll) GetEmpName() string {
	if x != nil {
		return x.EmpName
	}
	return ""
}

func (x *Payroll) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *Payroll) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type CreatePayrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmpId         string                 `protobuf:"bytes,1,opt,name=emp_id,json=empId,proto3" json:"emp_id,omitempty"`
	EmpName       string                 `protobuf:"bytes,2,opt,name=emp_name,json=empName,proto3" json:"emp_name,omitempty"`
	Salary        float64                `protobuf:"fixed64,3,opt,name=salary,proto3" json:"salary,omitempty"`
	Month         string                 `protobuf:"bytes,4,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePayrollRequest) Reset() {
	*x = CreatePayrollRequest{}
	mi := &file_payroll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePayrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePayrollRequest) ProtoMessage() {}

func (x *CreatePayrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePayrollRequest.ProtoReflect.Descriptor instead.
func (*CreatePayrollRequest) Descriptor() ([]byte, []int) {
	return file_payroll_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePayrollRequest) GetEmpId() string {
	if x != nil {
		return x.EmpId
	}
	return ""
}

func (x *CreatePayrollRequest) GetEmpName() string {
	if x != nil {
		return x.EmpName
	}
	return ""
}

func (x *CreatePayrollRequest) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *CreatePayrollRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type GetPayrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayrollRequest) Reset() {
	*x = GetPayrollRequest{}
	mi := &file_payroll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayrollRequest) ProtoMessage() {}

func (x *GetPayrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayrollRequest.ProtoReflect.Descriptor instead.
func (*GetPayrollRequest) Descriptor() ([]byte, []int) {
	return file_payroll_proto_rawDescGZIP(), []int{2}
}

func (x *GetPayrollRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdatePayrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmpName       string                 `protobuf:"bytes,2,opt,name=emp_name,json=empName,proto3" json:"emp_name,omitempty"`
	Salary        float64                `protobuf:"fixed64,3,opt,name=salary,proto3" json:"salary,omitempty"`
	Month         string                 `protobuf:"bytes,4,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePayrollRequest) Reset() {
	*x = UpdatePayrollRequest{}
	mi := &file_payroll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePayrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePayrollRequest) ProtoMessage() {}

func (x *UpdatePayrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePayrollRequest.ProtoReflect.Descriptor instead.
func (*UpdatePayrollRequest) Descriptor() ([]byte, []int) {
	return file_payroll_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePayrollRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePayrollRequest) GetEmpName() string {
	if x != nil {
		return x.EmpName
	}
	return ""
}

func (x *UpdatePayrollRequest) GetSalary() float64 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *UpdatePayrollRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type DeletePayrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePayrollRequest) Reset() {
	*x = DeletePayrollRequest{}
	mi := &file_payroll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePayrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePayrollRequest) ProtoMessage() {}

func (x *DeletePayrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePayrollRequest.ProtoReflect.Descriptor instead.
func (*DeletePayrollRequest) Descriptor() ([]byte, []int) {
	return file_payroll_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePayrollRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPayrollsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPayrollsRequest) Reset() {
	*x = ListPayrollsRequest{}
	mi := &file_payroll_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPayrollsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPayrollsRequest) ProtoMessage() {}

func (x *ListPayrollsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPayrollsRequest.ProtoReflect.Descriptor instead.
func (*ListPayrollsRequest) Descriptor() ([]byte, []int) {
	return file_payroll_proto_rawDescGZIP(), []int{5}
}

type ListPayrollsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payrolls      []*Payroll             `protobuf:"bytes,1,rep,name=payrolls,proto3" json:"payrolls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPayrollsResponse) Reset() {
	*x = ListPayrollsResponse{}
	mi := &file_payroll_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPayrollsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPayrollsResponse) ProtoMessage() {}

func (x *ListPayrollsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payroll_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPayrollsResponse.ProtoReflect.Descriptor instead.
func (*ListPayrollsResponse) Descriptor() ([]byte, []int) {
	return file_payroll_proto_rawDescGZIP(), []int{6}
}

func (x *ListPayrollsResponse) GetPayrolls() []*Payroll {
	if x != nil {
		return x.Payrolls
	}
	return nil
}

var File_payroll_proto protoreflect.FileDescriptor

const file_payroll_proto_rawDesc = "" +
	"\n" +
	"\rpayroll.proto\x12\apayroll\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"y\n" +
	"\aPayroll\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06emp_id\x18\x02 \x01(\tR\x05empId\x12\x19\n" +
	"\bemp_name\x18\x03 \x01(\tR\aempName\x12\x16\n" +
	"\x06salary\x18\x04 \x01(\x01R\x06salary\x12\x14\n" +
	"\x05month\x18\x05 \x01(\tR\x05month\"v\n" +
	"\x14CreatePayrollRequest\x12\x15\n" +
	"\x06emp_id\x18\x01 \x01(\tR\x05empId\x12\x19\n" +
	"\bemp_name\x18\x02 \x01(\tR\aempName\x12\x16\n" +
	"\x06salary\x18\x03 \x01(\x01R\x06salary\x12\x14\n" +
	"\x05month\x18\x04 \x01(\tR\x05month\"#\n" +
	"\x11GetPayrollRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\x14UpdatePayrollRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bemp_name\x18\x02 \x01(\tR\aempName\x12\x16\n" +
	"\x06salary\x18\x03 \x01(\x01R\x06salary\x12\x14\n" +
	"\x05month\x18\x04 \x01(\tR\x05month\"&\n" +
	"\x14DeletePayrollRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13ListPayrollsRequest\"D\n" +
	"\x14ListPayrollsResponse\x12,\n" +
	"\bpayrolls\x18\x01 \x03(\v2\x10.payroll.PayrollR\bpayrolls2\xe8\x03\n" +
	"\x0ePayrollService\x12Y\n" +
	"\rCreatePayroll\x12\x1d.payroll.CreatePayrollRequest\x1a\x10.payroll.Payroll\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/payrolls\x12U\n" +
	"\n" +
	"GetPayroll\x12\x1a.payroll.GetPayrollRequest\x1a\x10.payroll.Payroll\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/payrolls/{id}\x12^\n" +
	"\rUpdatePayroll\x12\x1d.payroll.UpdatePayrollRequest\x1a\x10.payroll.Payroll\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*2\x11/v1/payrolls/{id}\x12a\n" +
	"\rDeletePayroll\x12\x1d.payroll.DeletePayrollRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/payrolls/{id}\x12a\n" +
	"\fListPayrolls\x12\x1c.payroll.ListPayrollsRequest\x1a\x1d.payroll.ListPayrollsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/payrollsB$Z\"payroll_system/backend/proto;protob\x06proto3"

var (
	file_payroll_proto_rawDescOnce sync.Once
	file_payroll_proto_rawDescData []byte
)

func file_payroll_proto_rawDescGZIP() []byte {
	file_payroll_proto_rawDescOnce.Do(func() {
		file_payroll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payroll_proto_rawDesc), len(file_payroll_proto_rawDesc)))
	})
	return file_payroll_proto_rawDescData
}

var file_payroll_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_payroll_proto_goTypes = []any{
	(*Payroll)(nil),              // 0: payroll.Payroll
	(*CreatePayrollRequest)(nil), // 1: payroll.CreatePayrollRequest
	(*GetPayrollRequest)(nil),    // 2: payroll.GetPayrollRequest
	(*UpdatePayrollRequest)(nil), // 3: payroll.UpdatePayrollRequest
	(*DeletePayrollRequest)(nil), // 4: payroll.DeletePayrollRequest
	(*ListPayrollsRequest)(nil),  // 5: payroll.ListPayrollsRequest
	(*ListPayrollsResponse)(nil), // 6: payroll.ListPayrollsResponse
	(*emptypb.Empty)(nil),        // 7: google.protobuf.Empty
}
var file_payroll_proto_depIdxs = []int32{
	0, // 0: payroll.ListPayrollsResponse.payrolls:type_name -> payroll.Payroll
	1, // 1: payroll.PayrollService.CreatePayroll:input_type -> payroll.CreatePayrollRequest
	2, // 2: payroll.PayrollService.GetPayroll:input_type -> payroll.GetPayrollRequest
	3, // 3: payroll.PayrollService.UpdatePayroll:input_type -> payroll.UpdatePayrollRequest
	4, // 4: payroll.PayrollService.DeletePayroll:input_type -> payroll.DeletePayrollRequest
	5, // 5: payroll.PayrollService.ListPayrolls:input_type -> payroll.ListPayrollsRequest
	0, // 6: payroll.PayrollService.CreatePayroll:output_type -> payroll.Payroll
	0, // 7: payroll.PayrollService.GetPayroll:output_type -> payroll.Payroll
	0, // 8: payroll.PayrollService.UpdatePayroll:output_type -> payroll.Payroll
	7, // 9: payroll.PayrollService.DeletePayroll:output_type -> google.protobuf.Empty
	6, // 10: payroll.PayrollService.ListPayrolls:output_type -> payroll.ListPayrollsResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payroll_proto_init() }
func file_payroll_proto_init() {
	if File_payroll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payroll_proto_rawDesc), len(file_payroll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payroll_proto_goTypes,
		DependencyIndexes: file_payroll_proto_depIdxs,
		MessageInfos:      file_payroll_proto_msgTypes,
	}.Build()
	File_payroll_proto = out.File
	file_payroll_proto_goTypes = nil
	file_payroll_proto_depIdxs = nil
}
